### ISSUE TITLE
fix problem with calc AmountOut and problem with find poolId

### ISSUE THREAD

**Issue by kasrakhamesi** [raydium-io/raydium-sdk-V2-demo#4]
I have 2 question.
1.
https://github.com/raydium-io/raydium-sdk-V2-demo/issues/3
in this issue,I need find pool pair with search with back-end ( need exist that in this raydium-sdk-v2-demo ),but you tell me solution with raydium UI,but I need using it to find pool by baseMint and quoteMint in back-end

2.when using calcAmountOut in https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/amm/swap.ts

price has too different with https://raydium.io/swap

for example

if I want swap W-WSOL with amount : 1100
raydium UI show me  : 
![image](https://github.com/raydium-io/raydium-sdk-V2-demo/assets/80700084/7289aef3-0541-4681-95bc-2fb0134f38f8)

but /src/amm/swap.ts
show me 
![image](https://github.com/raydium-io/raydium-sdk-V2-demo/assets/80700084/bdb1c43c-99a8-49c2-8be0-9a95a543f443)

help me to fix it

**Comment by cruzshia** [comment]
1. update sdk version to 0.0.38-alpha and reference: [example](https://github.com/raydium-io/raydium-sdk-V2-demo?tab=readme-ov-file#fetch-pool-list-by-mints)
2. due to huge amount of pools in Raydium, swap in Raydium UI is calculated best route by backend, sdk doesn't support routing swap, only support swap example for different types of pools (e.g. amm/swap, clmm/swap, cpmm/swap), the code you used in only for amm pool swap calculation, you can compare different swap amount in these types of pools and find the best one.
