### ISSUE TITLE
raydium-sdk-V1-demo contains a subNewAmmPool example which is missing in v2

### ISSUE THREAD

**Issue by klauskobald** [raydium-io/raydium-sdk-V2-demo#97]
please, provide an example how to subscribe to pool events like 
any new pool created
any action that is happening with the pool
thank you

**Comment by cruzshia** [comment]
as I know subscribe to new created AMM pool isn't provide by SDK directly (https://github.com/raydium-io/raydium-sdk-V1-demo/blob/master/src/subNewAmmPool.ts)
SDK v2 also exports MARKET_STATE_LAYOUT_V3, SPL_MINT_LAYOUT that you can use, so you can write it by yourself and take reference to v1 demo.
I'll leave this issue if someone else has other thoughts on this.

**Comment by cruzshia** [comment]
https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/grpc/subNewAmmPool.ts

**Comment by lanseErd** [comment]
Why did none of the operations I performed here return any event messages? I'm not sure if the issue is with the RPC on Helius that I'm using. Here is my connection information: 

const client = new Client('https://mainnet.helius-rpc.com/?api-key=5ec7697b-2b8f-4383-807b-35b0bc27d43a', undefined, undefined) I have hardcoded this into my code.
